## 2.2.1一个简单的例子

In [1]:
import torch

x=torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [2]:
x.requires_grad_(True)   # 等价于x=torch.arange(4.0, requires_grad=True)
x.grad   # 默认值是None
y=2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [3]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [4]:
x.grad==4*x

tensor([True, True, True, True])

In [5]:
# 在默认情况下，PyTorch会累积梯度，所以在反向传播之后需要手动清零梯度
x.grad.zero_()
y=x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

## 2.5.2非标量变量的反向传播


In [6]:
# 对非标量调用backward()函数需要传入一个gradient参数，该参数指定微分函数关于self的梯度
# 本例只想求偏导数的和，所以传递一个1的梯度是合适的
x.grad.zero_()
y=x*x
# 等价与y.backward(torch.ones(len(x)))
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

## 2.5.3分离计算

In [7]:
# 清空张量x的梯度
x.grad.zero_() 
# 计算y为x的平方
y = x * x  
# 将y分离出计算图，避免y的梯度影响后续计算
u = y.detach() 
# 计算z为u和x的乘积
z = u * x  
# 对z的总和进行反向传播，计算x的梯度
z.sum().backward() 
# 检查x的梯度是否等于u
x.grad == u  


tensor([True, True, True, True])

In [8]:
# 清零x的梯度，以避免之前计算的梯度对后续计算产生影响
x.grad.zero_()
# 对y的总和进行反向传播，计算y相对于x的梯度
y.sum().backward()
# 检查当前x的梯度是否等于2*x，即验证反向传播的结果是否正确
x.grad == 2 * x

tensor([True, True, True, True])

## 2.5.4Python控制流的梯度计算

In [9]:
def f(a):
    b=a*2
    while b.norm()<1000:
        b=b*2
    if b.sum()>0:
        c=b
    else:
        c=100*b
    return c

In [10]:
a=torch.randn(size=(),requires_grad=True)
d=f(a)
d.backward()

In [11]:
a.grad==d/a

tensor(True)