## 5.4.1不带参数的层

In [1]:
import torch
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self,X):
        return X-X.mean()

In [2]:
layer=CenteredLayer()
layer(torch.FloatTensor([1,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
net=nn.Sequential(nn.Linear(8,128),CenteredLayer())
Y=net(torch.randn(4,8))
Y.mean()

tensor(-1.8626e-09, grad_fn=<MeanBackward0>)

## 5.4.2带参数的层

In [4]:
class MyLinear(nn.Module):
    def __init__(self,in_units,units):
        super().__init__()
        self.weight=nn.Parameter(torch.randn(in_units,units))
        self.bias=nn.Parameter(torch.randn(units,))
    def forward(self,X):
        linear=torch.matmul(X,self.weight.data)+ self.bias.data
        return F.relu(linear)

In [5]:
linear=MyLinear(5,3)
linear.weight

Parameter containing:
tensor([[ 0.4019,  0.2132,  0.4776],
        [-0.0913,  0.1752, -0.5107],
        [ 0.2014, -2.0916, -0.9453],
        [-0.3135, -0.1922, -0.3942],
        [-1.0073,  0.5170, -0.9539]], requires_grad=True)

In [6]:
linear(torch.randn(2,5))

tensor([[0.4901, 0.0000, 0.0000],
        [0.2807, 0.0000, 1.5885]])

In [7]:
net=nn.Sequential(MyLinear(64,8),MyLinear(8,1))
net(torch.randn(2,64))

tensor([[0.],
        [0.]])